# Generated by Django 4.1.7 on 2023-04-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_cart_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivery_charge',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
