# Generated by Django 4.1.7 on 2023-04-10 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_cart_delivery_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='delivery_charge',
        ),
    ]
